### ISSUE TITLE
log spam due to Yung's Bridges Forge

### ISSUE THREAD

**Issue by Wedge1453** [YUNG-GANG/YUNGs-Bridges#15] opened 2022-05-22 19:04 UTC
![Screenshot from 2022-05-22 14-48-02](https://user-images.githubusercontent.com/76813383/169711619-d5be90de-9c00-4c37-bca4-dacc1a7f64fe.png)

**Comment by yungnickyoung** [comment] 2022-07-28 01:44
Duplicate of #14

**Closed as completed** 2022-07-28 01:47 UTC
Labels: duplicate
